// Generated by Selenium IDE, но леко оправен за реален живот 😄
using System;
using System.Collections.Generic;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

[TestFixture]
public class TC01IfUserIsInvalidTryAgainTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        var options = new ChromeOptions();

        // ТОВА са аргументи към Chrome, не път към chromedriver:
        options.AddArgument("--headless=new");        // по-нов headless режим – идеален за Jenkins
        options.AddArgument("--no-sandbox");
        options.AddArgument("--disable-dev-shm-usage");
        options.AddArgument("--disable-gpu");

        // НЕ подаваме string път, оставяме Selenium да си намери драйвера
        driver = new ChromeDriver(options);

        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    public void TearDown()
    {
        if (driver != null)
        {
            try
            {
                driver.Quit();
            }
            catch
            {
                // ако вече е умрял, не ни пука
            }

            driver.Dispose();
            driver = null;
        }
    }

    [Test]
    public void TC01IfUserIsInvalidTryAgain()
    {
        // 1 | open | /
        driver.Navigate().GoToUrl("https://www.saucedemo.com/");

        // 2 | setWindowSize | 1552x832
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);

        // 3–5 | въвеждаме грешно потребителско име
        var username = driver.FindElement(By.CssSelector("*[data-test=\"username\"]"));
        username.Clear();
        username.SendKeys("user123");

        var password = driver.FindElement(By.CssSelector("*[data-test=\"password\"]"));
        password.Clear();
        password.SendKeys("secret_sauce");

        // 9 | click | login-button
        driver.FindElement(By.CssSelector("*[data-test=\"login-button\"]")).Click();

        // 10 | storeText | error | errorMessage
        vars["errorMessage"] = driver.FindElement(By.CssSelector("*[data-test=\"error\"]")).Text;

        // 11 | if | ${errorMessage} === "Epic sadface: Username and password do not match any user in this service"
        var isInvalidUserError = (bool)js.ExecuteScript(
            "return arguments[0] === 'Epic sadface: Username and password do not match any user in this service';",
            vars["errorMessage"]);

        if (isInvalidUserError)
        {
            Console.WriteLine("Wrong username");

            // 13–15 | изчистваме user и логваме с коректен
            username = driver.FindElement(By.CssSelector("*[data-test=\"username\"]"));
            username.Clear();
            username.SendKeys("standard_user");

            driver.FindElement(By.CssSelector("*[data-test=\"login-button\"]")).Click();

            // 16 | assertText | title | Products
            Assert.That(
                driver.FindElement(By.CssSelector("*[data-test=\"title\"]")).Text,
                Is.EqualTo("Products"));

            Console.WriteLine("Successful login");
        }

        // Не затваряме тук – TearDown() ще се погрижи за драйвера.
    }
}
